### ISSUE TITLE
Support for spring beans in expressions

### ISSUE THREAD

**Issue by lukashinsch** [jirutka/validator-spring#2]
It would be great to be able to reference arbitrary spring beans in validation expressions (i.e. calling services methods etc.).
```
@SpELAssert("@myService.checkForSomething(#myProperty)")
```
It's actually quite easy to do (I have a working prototype) by adding a BeanResolver to the expression parser.
I could prepare a PR if you are interested to include this feature.

**Comment by jirutka** [comment]
Thanks for the suggestion. I’m definitely interested, please send a PR! :smile_cat:

**Comment by lukashinsch** [comment]
Hi Jakub,

please see references PR for a suggested solution.

BR
Lukas
