### ISSUE TITLE
Does this support jsr 303 bean validation groups?

### ISSUE THREAD

**Issue by cm325** [jirutka/validator-spring#5]
For any validation annotation to be useful in our applications, it has to support the bean validation groups,  so that we can run validation on a request by request basis and only run the validations we need for a specific group. If this supported groups, we would start using it immediately!

**Comment by jirutka** [comment]
Yes, it support validation groups.

**Comment by cm325** [comment]
Interesting, I didn't see any examples in the documentation? Is it as
sample as including the groups={ Employee.class, Contractor.class }
attribute in the annotation?

**Comment by jirutka** [comment]
This isn’t responsibility of validation constraint, but Bean Validation framework. Constraint annotation must define `groups()` attribute ([here](https://github.com/jirutka/validator-spring/blob/7241dfbd08f6bd93336d2f91b231dd8f0c55786b/src/main/java/cz/jirutka/validator/spring/SpELAssert.java#L47)) and that’s all.
