### ISSUE TITLE
alllow several variable assigments in expression

### ISSUE THREAD

**Issue by cforce** [jirutka/validator-spring#6]
How can i set defaults on more than one member on a class level evaluation expression?
I made the experience that ;,  () and {} are not allowed, so it's not possible to have several variable assigments in one expression.

**Comment by jirutka** [comment]
Could you please provide an example of what you want to achieve?

**Comment by cforce** [comment]
http://stackoverflow.com/questions/33540566/howto-do-validate-and-do-several-assignments-in-same-spel-expression

**Comment by jirutka** [comment]
Oh my… this is really horrible abuse of SpEL… I recommend you to extract this complex validation logic into utility methods and use them as described [here](https://github.com/jirutka/validator-spring#using-helper-functions).

**Comment by cforce** [comment]
I decided i will do the validation with JSR303 and Customvalidators separtely, because i don't see as much advantage in SPEL over Standard JSR303 capabilities - do you?

**Comment by jirutka** [comment]
I do, it requires a lot of unnecessary boilerplate. However, your validation logic is quite complex and you should externalize it anyway, so SpEL validator may not be best choice for you in this case.

**Comment by cforce** [comment]
I need to export the validation logic as documentation in REST API and need to be  able to reuse the validtions at API GAteway microservice without having to share a common class libary in API Gateway and destinatipon microrservice. That was the origin of the idea to have it externalized as configuration (SPEL setting).
