### ISSUE TITLE
SpELAssert not working on fields

### ISSUE THREAD

**Issue by e-g-hategan** [jirutka/validator-spring#9]
Using SpELAsssert 1.1.0 and Spring Boot 1.3.6.

SpELAsserts work fine at type level but the equivalent ones don't work at all at field level.

WORKS
`@SpELAssert("value != null")
class TypeAssertedRequest {
  public String value;
}`

DOESN'T WORK
`class FieldAssertedRequest {
  @SpELAssert("#this != null")
  public String value;
}`

I've also put together a [small maven project](https://github.com/e-g-hategan/SpELAssertBug) to reproduce it.

**Comment by aristotll** [comment]
It seems that all null values are considered valid.
See https://github.com/jirutka/validator-spring/blob/5f89f5e910feaa790f79eed272bb3d386131b048/src/main/java/cz/jirutka/validator/spring/SpELAssertValidator.java#L80-L81

**Comment by e-g-hategan** [comment]
Thanks for looking into this @aristotll 
I guess that's fair, many implementations of constraint validators do the same. 

The workaround is to have an additional `@NotNull` validator like below: 
 `class FieldAssertedRequest { @NotNull @SpELAssert("#this != null") public String value; }`
